CREATE TABLE CLIENT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100)
);
CREATE TABLE PRODUCT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(255),
    UNITARY_VALUE DECIMAL(20, 2)
);
CREATE TABLE REQUEST (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID BIGINT REFERENCES CLIENT (ID),
    REQUEST_DATE TIMESTAMP,
    AMOUNT NUMERIC(20, 2)
);
CREATE TABLE ITEM_REQUEST (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    REQUEST_ID BIGINT REFERENCES REQUEST (ID),
    PRODUCT_ID BIGINT REFERENCES PRODUCT (ID),
    AMOUNT NUMERIC(20, 2)
);